2018-05-29 10:14:33 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.cdszgdx.com>: Connection was refused by other side: 111: Connection refused.
2018-05-29 10:14:36 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.cnzx.com.cn>: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2018-05-29 10:14:56 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.dysyzx.net>: Connection was refused by other side: 111: Connection refused.
2018-05-29 10:14:56 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.dyqdszx.net>: Connection was refused by other side: 111: Connection refused.
2018-05-29 10:14:58 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.fdfz.cn/>: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]>]
2018-05-29 10:15:27 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.hbxgyz.cn>: Connection was refused by other side: 111: Connection refused.
2018-05-29 10:15:47 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.cyyz.com.cn>
Traceback (most recent call last):
  File "/home/python/.virtualenvs/spider_py3/lib/python3.5/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/python/.virtualenvs/spider_py3/lib/python3.5/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/python/.virtualenvs/spider_py3/lib/python3.5/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "/home/python/.virtualenvs/spider_py3/lib/python3.5/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/python/.virtualenvs/spider_py3/lib/python3.5/site-packages/twisted/internet/endpoints.py", line 954, in startConnectionAttempts
    "no results for hostname lookup: {}".format(self._hostStr)
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.cyyz.com.cn.
2018-05-29 10:15:49 [scrapy.core.scraper] ERROR: Error downloading <GET http://www.czyz.com.cn>
Traceback (most recent call last):
  File "/home/python/.virtualenvs/spider_py3/lib/python3.5/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/python/.virtualenvs/spider_py3/lib/python3.5/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/python/.virtualenvs/spider_py3/lib/python3.5/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "/home/python/.virtualenvs/spider_py3/lib/python3.5/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/python/.virtualenvs/spider_py3/lib/python3.5/site-packages/twisted/internet/endpoints.py", line 954, in startConnectionAttempts
    "no results for hostname lookup: {}".format(self._hostStr)
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: www.czyz.com.cn.
